language: c

install:
        - wget https://nexus.zephyrproject.org/content/repositories/releases/org/zephyrproject/zephyr-sdk/0.8.2-i686/zephyr-sdk-0.8.2-i686-setup.run -O /tmp/zephyr-sdk.run
        - chmod a+x /tmp/zephyr-sdk.run
        - sudo /tmp/zephyr-sdk.run -- -d /opt/zephyr-sdk/

script:
        - pwd
        - export ZEPHYR_GCC_VARIANT=zephyr
        - export ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
        - source zephyr-env.sh
        - ./scripts/sanitycheck
