/*******************************************************************************
* File Name: cycfg_pins.h
*
* Description:
* Pin configuration
* This file should not be modified. It was automatically generated by
* ModusToolbox 1.0.0
*
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CYCFG_PINS_H)
#define CYCFG_PINS_H

#include "notices.h"
#include "cy_gpio.h"
#include "cycfg_connectivity.h"

#if defined(__cplusplus)
extern "C" {
#endif

#define LED_RED_PORT GPIO_PRT0
#define LED_RED_PIN 3U
#define LED_RED_NUM 3U
#define LED_BLUE_PORT GPIO_PRT11
#define LED_BLUE_PIN 1U
#define LED_BLUE_NUM 1U
#define ioss_0__port_6__pin_4__PORT GPIO_PRT6
#define ioss_0__port_6__pin_4__PIN 4U
#define ioss_0__port_6__pin_4__NUM 4U
#define ioss_0__port_6__pin_6__PORT GPIO_PRT6
#define ioss_0__port_6__pin_6__PIN 6U
#define ioss_0__port_6__pin_6__NUM 6U
#define ioss_0__port_6__pin_7__PORT GPIO_PRT6
#define ioss_0__port_6__pin_7__PIN 7U
#define ioss_0__port_6__pin_7__NUM 7U

extern const cy_stc_gpio_pin_config_t LED_RED_cfg;
extern const cy_stc_gpio_pin_config_t LED_BLUE_cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_6__pin_4__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_6__pin_6__cfg;
extern const cy_stc_gpio_pin_config_t ioss_0__port_6__pin_7__cfg;


#if defined(__cplusplus)
}
#endif


#endif /* CYCFG_PINS_H */
