/*
 * Copyright (c) 2014 Wind River Systems, Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Linker command/script file
 *
 * This is the linker script for both standard images and XIP images.
 */

#include <autoconf.h>

#include <arch/arm/cortex_m/scripts/linker.ld>

/* #include <d:/Security/zephyr/ext/hal/cypress/PDL/3.1.0/devices/psoc6/linker/armgcc/cy8c6xx7_cm0plus.ld> */